# Configuración para proyecto Angular
sonar.projectKey=inventario
sonar.projectName=inventario
sonar.projectVersion=1.0

# Fuentes a analizar
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

# Configuración TypeScript
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8

# Excluir archivos
sonar.exclusions=**/node_modules/**, **/*.json, **/environments/**

# Conexión a SonarQube
sonar.host.url=http://localhost:9000
sonar.login=sqp_f35731c6d5e5765044bbd527f8b1a84edf44358c